# Generated by Django 2.2.1 on 2019-05-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatag',
            name='description',
            field=models.CharField(db_index=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='metatag',
            name='title',
            field=models.CharField(db_index=True, max_length=80),
        ),
    ]
