# Generated by Django 2.2.1 on 2019-05-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190520_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('desc', models.TextField(blank=True, db_index=True)),
                ('button_one_desc', models.CharField(db_index=True, max_length=200)),
                ('button_one_slug', models.SlugField(max_length=200, unique=True)),
                ('button_two_desc', models.CharField(db_index=True, max_length=200)),
                ('button_two_slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
    ]
