# Generated by Django 2.2.1 on 2019-05-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blockone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockone',
            name='button_one_desc',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='blockone',
            name='button_one_slug',
            field=models.SlugField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='blockone',
            name='button_two_desc',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='blockone',
            name='button_two_slug',
            field=models.SlugField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='blockone',
            name='title',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
