# Generated by Django 2.2.1 on 2019-05-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190520_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockone',
            name='button_one_slug',
        ),
        migrations.RemoveField(
            model_name='blockone',
            name='button_two_slug',
        ),
        migrations.AddField(
            model_name='blockone',
            name='button_one_url',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockone',
            name='button_two_url',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
