# Generated by Django 2.2.1 on 2019-05-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190521_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='db_footer_desc',
            new_name='footer_desc',
        ),
    ]
