# Generated by Django 2.2.1 on 2019-05-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190521_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer_desc',
            name='facebook_url',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='footer_desc',
            name='instagram_url',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='footer_desc',
            name='youtube_url',
            field=models.CharField(max_length=10000),
        ),
    ]
