# Generated by Django 2.2.1 on 2019-05-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_footer_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer_bg',
            name='image',
            field=models.ImageField(blank=True, help_text='70x70px', upload_to='media/images/home/%Y/%m/%d', verbose_name='Ссылка картинки'),
        ),
    ]
