# Generated by Django 2.2.1 on 2019-05-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190521_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer_bg',
            name='image',
        ),
        migrations.AddField(
            model_name='footer_bg',
            name='footer_bg',
            field=models.ImageField(blank=True, help_text='70x70px', upload_to='media/images/home/%Y', verbose_name='Ссылка картинки'),
        ),
    ]
