# Generated by Django 2.2.1 on 2019-05-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190521_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='footer_bg',
        ),
    ]
