# Generated by Django 2.2.1 on 2019-05-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_delete_footer_bg'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('desc_top', models.TextField(blank=True)),
                ('strong', models.CharField(max_length=80)),
                ('lists', models.CharField(max_length=200)),
                ('desc_bottom', models.TextField(blank=True)),
            ],
        ),
    ]
