# Generated by Django 2.2.1 on 2019-05-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190521_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/home/workBlock/%Y')),
            ],
        ),
    ]
