# Generated by Django 2.2.1 on 2019-05-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_workimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatag',
            name='title',
            field=models.CharField(db_index=True, max_length=80, verbose_name='Тайт для главной страницы'),
        ),
    ]
