# Generated by Django 2.2.1 on 2019-05-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190521_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockone',
            name='button_one_desc',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='Описания для первой кнопки'),
        ),
        migrations.AlterField(
            model_name='blockone',
            name='button_one_url',
            field=models.CharField(max_length=1000, verbose_name='URL для первой кнопки'),
        ),
        migrations.AlterField(
            model_name='blockone',
            name='button_two_desc',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='Описание для второй кнопки'),
        ),
        migrations.AlterField(
            model_name='blockone',
            name='button_two_url',
            field=models.CharField(max_length=1000, verbose_name='URL для второй кнопки'),
        ),
        migrations.AlterField(
            model_name='blockone',
            name='desc',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание для первого блока'),
        ),
        migrations.AlterField(
            model_name='blockone',
            name='title',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='H1 для первого блока'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Заголовок меню'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(max_length=800, verbose_name='URL адресс (http://simple.com/...'),
        ),
        migrations.AlterField(
            model_name='metatag',
            name='description',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание для главной страницы'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=250, verbose_name='Номер телефона для главной'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='tag',
            field=models.CharField(max_length=250, verbose_name='Тег телефона для ссылки (0930000000)'),
        ),
        migrations.AlterField(
            model_name='workblock',
            name='desc_bottom',
            field=models.TextField(blank=True, verbose_name='Описание внизу второго блока'),
        ),
        migrations.AlterField(
            model_name='workblock',
            name='desc_top',
            field=models.TextField(blank=True, verbose_name='Описание вверху второго блока'),
        ),
        migrations.AlterField(
            model_name='workblock',
            name='title',
            field=models.CharField(max_length=400, verbose_name='H2 для второго блока'),
        ),
        migrations.AlterField(
            model_name='workimg',
            name='image',
            field=models.ImageField(upload_to='media/images/home/workBlock/%Y', verbose_name='Картинка второго блока'),
        ),
        migrations.AlterField(
            model_name='worklist',
            name='lists',
            field=models.CharField(max_length=200, verbose_name='Элемент списка выделеный не жырным (текс)'),
        ),
        migrations.AlterField(
            model_name='worklist',
            name='strong',
            field=models.CharField(max_length=80, verbose_name='Элемент списка выделеный жирным (7 лет)'),
        ),
    ]
