# Generated by Django 2.2.1 on 2019-05-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190521_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workimg',
            name='image',
            field=models.ImageField(upload_to='images/home/workBlock/%Y', verbose_name='Картинка второго блока'),
        ),
    ]
