# Generated by Django 2.2.1 on 2019-05-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20190521_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_title', models.CharField(max_length=800, verbose_name='Заголовок услуг')),
                ('common_desc', models.TextField(blank=True, verbose_name='Описание услуг')),
                ('s_one_title', models.CharField(max_length=800, verbose_name='Заголовок первой услуги')),
                ('s_one_desc', models.TextField(blank=True, verbose_name='Описание первой услуг')),
                ('s_one_url', models.CharField(max_length=5000, verbose_name='Ссылка первой услуги')),
                ('s_two_title', models.CharField(max_length=800, verbose_name='Заголовок второй услуги')),
                ('s_two_desc', models.TextField(blank=True, verbose_name='Описание второй услуг')),
                ('s_two_url', models.CharField(max_length=5000, verbose_name='Ссылка второй услуги')),
                ('s_three_title', models.CharField(max_length=800, verbose_name='Заголовок третей услуги')),
                ('s_three_desc', models.TextField(blank=True, verbose_name='Описание третей услуг')),
                ('s_three_url', models.CharField(max_length=5000, verbose_name='Ссылка третей услуги')),
                ('s_four_title', models.CharField(max_length=800, verbose_name='Заголовок четвертой услуги')),
                ('s_four_desc', models.TextField(blank=True, verbose_name='Описание четвертой услуг')),
                ('s_four_url', models.CharField(max_length=5000, verbose_name='Ссылка четвертой услуги')),
                ('s_five_title', models.CharField(max_length=800, verbose_name='Заголовок пятой услуги')),
                ('s_five_desc', models.TextField(blank=True, verbose_name='Описание пятой услуг')),
                ('s_five_url', models.CharField(max_length=5000, verbose_name='Ссылка пятой услуги')),
            ],
        ),
    ]
