# Generated by Django 2.2.1 on 2019-05-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20190522_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesblock',
            name='s_five_url',
            field=models.CharField(max_length=1000, verbose_name='Ссылка пятой услуги'),
        ),
        migrations.AlterField(
            model_name='servicesblock',
            name='s_four_url',
            field=models.CharField(max_length=1000, verbose_name='Ссылка четвертой услуги'),
        ),
        migrations.AlterField(
            model_name='servicesblock',
            name='s_one_url',
            field=models.CharField(max_length=1000, verbose_name='Ссылка первой услуги'),
        ),
        migrations.AlterField(
            model_name='servicesblock',
            name='s_three_url',
            field=models.CharField(max_length=1000, verbose_name='Ссылка третей услуги'),
        ),
        migrations.AlterField(
            model_name='servicesblock',
            name='s_two_url',
            field=models.CharField(max_length=1000, verbose_name='Ссылка второй услуги'),
        ),
    ]
