# Generated by Django 2.2.1 on 2019-05-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20190522_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesblock',
            name='bg_image',
            field=models.ImageField(blank=True, upload_to='images/home/ServicesBlock/%Y', verbose_name='Задний фон блока услуг'),
        ),
    ]
