# Generated by Django 2.2.1 on 2019-05-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_servicesblock_bg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800, verbose_name='Заголовок блока')),
                ('desc', models.TextField(blank=True, verbose_name='Описание блока')),
                ('item_title', models.CharField(max_length=800, verbose_name='Заголовок элемента')),
                ('item_desc', models.TextField(blank=True, verbose_name='Описание элемента')),
                ('button_url', models.CharField(blank=True, max_length=800, verbose_name='Ссылка кнопки')),
                ('item_color', models.CharField(max_length=800, verbose_name='Цвет подложки')),
            ],
        ),
    ]
