# Generated by Django 2.2.1 on 2019-05-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_portfolioblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=800, verbose_name='Заголовок элемента')),
                ('item_desc', models.TextField(blank=True, verbose_name='Описание элемента')),
                ('button_url', models.CharField(blank=True, max_length=800, verbose_name='Ссылка кнопки')),
                ('item_color', models.CharField(max_length=800, verbose_name='Цвет подложки')),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolioblock',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='portfolioblock',
            name='item_color',
        ),
        migrations.RemoveField(
            model_name='portfolioblock',
            name='item_desc',
        ),
        migrations.RemoveField(
            model_name='portfolioblock',
            name='item_title',
        ),
    ]
