# Generated by Django 2.2.1 on 2019-05-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20190522_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioblock',
            name='img',
            field=models.ImageField(default=0, upload_to='images/home/portfolioBlock/%Y', verbose_name='Картинка элемента'),
            preserve_default=False,
        ),
    ]
