# Generated by Django 2.2.1 on 2019-05-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_portfolioblock_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioblock',
            name='desc_width',
            field=models.CharField(default=0, max_length=800, verbose_name='Заголовок блока'),
            preserve_default=False,
        ),
    ]
