# Generated by Django 2.2.1 on 2019-05-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_portfolioblock_desc_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioblock',
            name='desc_width',
            field=models.IntegerField(default=100, verbose_name='Размер блока в %'),
        ),
    ]
