# Generated by Django 2.2.1 on 2019-05-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20190522_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioblock',
            name='button_url',
            field=models.CharField(default=0, max_length=800, verbose_name='Все проекты url'),
            preserve_default=False,
        ),
    ]
