# Generated by Django 2.2.1 on 2019-05-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_portfolioblock_button_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioblock',
            name='img',
        ),
        migrations.AddField(
            model_name='portfolioimg',
            name='img',
            field=models.ImageField(default=0, upload_to='images/home/portfolioBlock/%Y', verbose_name='Картинка элемента'),
            preserve_default=False,
        ),
    ]
