# Generated by Django 2.2.1 on 2019-05-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20190523_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockone',
            options={'verbose_name': 'Первый блок', 'verbose_name_plural': 'Первый блок'},
        ),
    ]
