# Generated by Django 2.2.1 on 2019-05-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20190523_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockone',
            options={'verbose_name': 'Первый блок - Офер (H1, описание, кнопки)', 'verbose_name_plural': 'Первый блок - Офер'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню сайта', 'verbose_name_plural': 'Меню сайта'},
        ),
        migrations.AlterModelOptions(
            name='metatag',
            options={'verbose_name': 'Мета-теги главной (Title and desc)', 'verbose_name_plural': 'Мета-теги главной'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Телефон - Меню (Телефон в меню)', 'verbose_name_plural': 'Телефон - Меню'},
        ),
        migrations.AlterModelOptions(
            name='portfolioblock',
            options={'verbose_name': 'Четвертый блок - Портфолио (Заголово, описание)', 'verbose_name_plural': 'Четвертый блок сайта'},
        ),
        migrations.AlterModelOptions(
            name='portfolioimg',
            options={'verbose_name': 'Четвертый блок - Портфолио (Элементы, изображения)', 'verbose_name_plural': 'Четвертый блок сайта'},
        ),
        migrations.AlterModelOptions(
            name='reviewsblock',
            options={'verbose_name': 'Пятый блок - Отзывы (Заголовок, описание, задний фон)', 'verbose_name_plural': 'Пятый блок - Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='servicesblock',
            options={'verbose_name': 'Третий блок - Услуги (Описание сайта, описание услуг)', 'verbose_name_plural': 'Третий блок - Услуги'},
        ),
        migrations.AlterModelOptions(
            name='workblock',
            options={'verbose_name': 'Второй блок - Наши клиенты (Заголовко, описание)', 'verbose_name_plural': 'Второй блок сайта'},
        ),
        migrations.AlterModelOptions(
            name='workimg',
            options={'verbose_name': 'Второй блок - Наши клиенты (Логотипы клиентов)', 'verbose_name_plural': 'Второй блок сайта'},
        ),
        migrations.AlterModelOptions(
            name='worklist',
            options={'verbose_name': 'Второй блок - Наши клиенты (Список достижений)', 'verbose_name_plural': 'Второй блок сайта'},
        ),
    ]
