# Generated by Django 2.2.1 on 2019-05-23 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20190523_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer_desc',
            options={'verbose_name': 'Футер сайта (Лого, описание, соц. сети)', 'verbose_name_plural': 'Пятый блок - Отзывы'},
        ),
    ]
