# Generated by Django 2.2.1 on 2019-05-23 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20190523_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockone',
            options={'verbose_name': 'Первый блок - Офер (H1, описание, кнопки)', 'verbose_name_plural': 'Первый блок - Офер (H1, описание, кнопки)'},
        ),
        migrations.AlterModelOptions(
            name='footer_desc',
            options={'verbose_name': 'Футер сайта (Лого, описание, соц. сети)', 'verbose_name_plural': 'Футер сайта (Лого, описание, соц. сети)'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Телефон - Меню (Телефон в меню)', 'verbose_name_plural': 'Телефон - Меню (Телефон в меню)'},
        ),
        migrations.AlterModelOptions(
            name='portfolioblock',
            options={'verbose_name': 'Четвертый блок - Портфолио (Заголово, описание)', 'verbose_name_plural': 'Четвертый блок - Портфолио (Заголово, описание)'},
        ),
        migrations.AlterModelOptions(
            name='portfolioimg',
            options={'verbose_name': 'Четвертый блок - Портфолио (Элементы, изображения)', 'verbose_name_plural': 'Четвертый блок - Портфолио (Элементы, изображения)'},
        ),
        migrations.AlterModelOptions(
            name='reviewsblock',
            options={'verbose_name': 'Пятый блок - Отзывы (Заголовок, описание, задний фон)', 'verbose_name_plural': 'Пятый блок - Отзывы (Заголовок, описание, задний фон)'},
        ),
        migrations.AlterModelOptions(
            name='servicesblock',
            options={'verbose_name': 'Третий блок - Услуги (Описание сайта, описание услуг)', 'verbose_name_plural': 'Третий блок - Услуги (Описание сайта, описание услуг)'},
        ),
        migrations.AlterModelOptions(
            name='workblock',
            options={'verbose_name': 'Второй блок - Наши клиенты (Заголовко, описание)', 'verbose_name_plural': 'Второй блок - Наши клиенты (Заголовко, описание)'},
        ),
        migrations.AlterModelOptions(
            name='workimg',
            options={'verbose_name': 'Второй блок - Наши клиенты (Логотипы клиентов)', 'verbose_name_plural': 'Второй блок - Наши клиенты (Логотипы клиентов)'},
        ),
        migrations.AlterModelOptions(
            name='worklist',
            options={'verbose_name': 'Второй блок - Наши клиенты (Список достижений)', 'verbose_name_plural': 'Второй блок - Наши клиенты (Список достижений)'},
        ),
    ]
