# Generated by Django 2.2.1 on 2019-05-23 09:52

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_reviewsitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioimg',
            name='item_color',
            field=colorful.fields.RGBColorField(),
        ),
    ]
