# Generated by Django 2.2.1 on 2019-05-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_reviewsitem_awesome_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsblock',
            name='btn_url',
            field=models.CharField(default=0, max_length=2000, verbose_name='Ссылка на все отзывы'),
            preserve_default=False,
        ),
    ]
