# Generated by Django 2.2.1 on 2019-05-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_teamblock_teamitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamblock',
            name='desc_width',
            field=models.IntegerField(default=100, verbose_name='Описание блока - размер'),
        ),
    ]
